#
# Builder
#

FROM golang:alpine AS builder

WORKDIR /watchtower
COPY go.mod .
COPY go.sum .
RUN go mod download

RUN apk add --no-cache \
    alpine-sdk \
    ca-certificates \
    git \
    tzdata

COPY . /watchtower

RUN \
  cd /watchtower && \
  \
  GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-extldflags '-static' -X github.com/containrrr/watchtower/internal/meta.Version=$(git describe --tags)" . && \
  GO111MODULE=on go test ./... -v


#
# watchtower
#

FROM alpine:3.21

LABEL "com.centurylinklabs.watchtower"="true"

RUN apk add --no-cache \
        ca-certificates \
        tzdata \
        python3 \
        py3-pip \
    && pip3 install --no-cache-dir --break-system-packages "apprise==1.9.3" \
    && apk del --no-network py3-pip \
    && find /usr -type d -name '__pycache__' -prune -exec rm -rf {} + || true \
    && rm -rf /root/.cache /tmp/* /var/cache/apk/*

COPY --from=builder /watchtower/watchtower /watchtower

EXPOSE 8080

HEALTHCHECK CMD [ "/watchtower", "--health-check"]

ENTRYPOINT ["/watchtower"]
