#
# Builder
#

FROM golang:alpine as builder

# use version (for example "v1.7.2") or "main"
ARG WATCHTOWER_VERSION=main
ARG WATCHTOWER_REPO=https://github.com/dallergy/watchtower.git

RUN apk add --no-cache \
    alpine-sdk \
    ca-certificates \
    git \
    tzdata

RUN git clone --branch "${WATCHTOWER_VERSION}" "${WATCHTOWER_REPO}"

RUN \
  cd watchtower && \
  \
  GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-extldflags '-static' -X github.com/containrrr/watchtower/internal/meta.Version=$(git describe --tags)" . && \
  GO111MODULE=on go test ./... -v


#
# watchtower
#

FROM scratch

LABEL "com.centurylinklabs.watchtower"="true"

# copy files from other container
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /go/watchtower/watchtower /watchtower

HEALTHCHECK CMD [ "/watchtower", "--health-check"]

ENTRYPOINT ["/watchtower"]
