name: Greetings

on:
  # Runs in the context of the base repository, and as such has access to GITHUB_TOKEN
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        issue_message: >
          Hi there! 👋🏼
          As you're new to this repo, we'd like to suggest that you read our
          [contribution guidelines](https://github.com/dallergy/watchtower/blob/main/CONTRIBUTING.md).
          Thanks a bunch for opening your first issue! 🙏
        pr_message: >
          Congratulations on opening your first pull request! We'll get back to you as soon as possible. In the meantime, please make sure you've updated the documentation to reflect your changes and have added test automation as needed. Thanks! 🙏🏼
